In [23]:
import sklearn
from sklearn.utils import shuffle
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
import pandas as pd
import numpy as np
import sklearn.metrics as met
import matplotlib.pyplot as plt
import sklearn.model_selection as ms
import pickle

In [24]:
from google.colab import drive
drive.mount('/content/drive')
drive.mount('/content/drive', force_remount=True)
!ls '/content/drive/MyDrive/car.data'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Mounted at /content/drive
/content/drive/MyDrive/car.data


In [25]:
data = pd.read_csv('/content/drive/MyDrive/car.data')
df = pd.DataFrame(data)
df.head()

buying  maint doors persons lug_boot safty  class
0  vhigh  vhigh     2       2    small   low  unacc
1  vhigh  vhigh     2       2    small   med  unacc
2  vhigh  vhigh     2       2    small  high  unacc
3  vhigh  vhigh     2       2      med   low  unacc
4  vhigh  vhigh     2       2      med   med  unacc

In [26]:
df.columns

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safty', 'class'], dtype='object')

In [27]:
le = preprocessing.LabelEncoder()

In [28]:
buying = le.fit_transform(list(df['buying']))
maint = le.fit_transform(list(df['maint']))
doors = le.fit_transform(list(df['doors']))
persons = le.fit_transform(list(df['persons']))
lugboot = le.fit_transform(list(df['lug_boot']))
safty = le.fit_transform(list(df['safty']))

In [29]:
clss = le.fit_transform(list(df['class']))

In [30]:
x = list(zip(buying, maint, doors, persons, lugboot, safty)) # feature
y = list(clss) #label

In [31]:
x_train, x_test, y_train, y_test = ms.train_test_split(x, y, test_size=0.1)

In [32]:
model = KNeighborsClassifier(n_neighbors=7)

In [33]:
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [34]:
model.score(x_test, y_test)

0.9421965317919075

In [35]:
model.score(x_train, y_train)

0.9665594855305466

In [36]:
predicted = model.predict(x_test)

In [37]:
clas = ["unacc", "acc", "good", "vgood"]

In [38]:
for x in range (len(predicted)):
  print("pred:", clas[predicted[x]], "real:", clas[y_test[x]])
  n = model.kneighbors([x_test[x]], 3)
  print("-----------------------------------------------------------")
  print(n)

pred: good real: good
-----------------------------------------------------------
(array([[1., 1., 1.]]), array([[ 53, 823, 186]]))
pred: unacc real: unacc
-----------------------------------------------------------
(array([[1., 1., 1.]]), array([[ 413, 1296, 1027]]))
pred: acc real: acc
-----------------------------------------------------------
(array([[1., 1., 1.]]), array([[  45, 1389,   25]]))
pred: good real: good
-----------------------------------------------------------
(array([[1., 1., 1.]]), array([[1436, 1214,  330]]))
pred: unacc real: vgood
-----------------------------------------------------------
(array([[1., 1., 1.]]), array([[666, 284, 322]]))
pred: good real: good
-----------------------------------------------------------
(array([[1., 1., 1.]]), array([[103, 224, 634]]))
pred: good real: good
-----------------------------------------------------------
(array([[1., 1., 1.]]), array([[1137,  806,  874]]))
pred: good real: good
----------------------------------------