In [1]:
import sklearn
from sklearn.utils import shuffle
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
import pandas as pd
import numpy as np
import sklearn.metrics as met
import matplotlib.pyplot as plt
import sklearn.model_selection as ms
import pickle

In [3]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
!ls '/content/drive/MyDrive/car.data'

Mounted at /content/drive
/content/drive/MyDrive/car.data


In [4]:
data = pd.read_csv('/content/drive/MyDrive/car.data')
df = pd.DataFrame(data)
df.head()

buying  maint doors persons lug_boot safty  class
0  vhigh  vhigh     2       2    small   low  unacc
1  vhigh  vhigh     2       2    small   med  unacc
2  vhigh  vhigh     2       2    small  high  unacc
3  vhigh  vhigh     2       2      med   low  unacc
4  vhigh  vhigh     2       2      med   med  unacc

In [5]:
df.columns

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safty', 'class'], dtype='object')

In [6]:
le = preprocessing.LabelEncoder()

In [7]:
buying = le.fit_transform(list(df['buying']))
maint = le.fit_transform(list(df['maint']))
doors = le.fit_transform(list(df['doors']))
persons = le.fit_transform(list(df['persons']))
lugboot = le.fit_transform(list(df['lug_boot']))
safty = le.fit_transform(list(df['safty']))

In [8]:
clss = le.fit_transform(list(df['class']))

In [9]:
x = list(zip(buying, maint, doors, persons, lugboot, safty)) # feature
y = list(clss) #label

In [19]:
x_train, x_test, y_train, y_test = ms.train_test_split(x, y, test_size=0.05)

In [26]:
model = KNeighborsClassifier(n_neighbors=9)

In [27]:
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=9)

In [28]:
model.score(x_test, y_test)

0.9770114942528736

In [29]:
model.score(x_train, y_train)

0.9786715417428398

In [30]:
predicted = model.predict(x_test)

In [31]:
clas = ["unacc", "acc", "good", "vgood"]

In [32]:
for x in range (len(predicted)):
  print("pred:", clas[predicted[x]], "real:", clas[y_test[x]])
  n = model.kneighbors([x_test[x]], 3)
  print("-----------------------------------------------------------")
  print(n)

pred: good real: good
-----------------------------------------------------------
(array([[1., 1., 1.]]), array([[186,  16, 390]]))
pred: good real: good
-----------------------------------------------------------
(array([[1., 1., 1.]]), array([[219, 487,   8]]))
pred: good real: good
-----------------------------------------------------------
(array([[1., 1., 1.]]), array([[1357, 1350, 1063]]))
pred: good real: good
-----------------------------------------------------------
(array([[1., 1., 1.]]), array([[ 458, 1390, 1568]]))
pred: good real: good
-----------------------------------------------------------
(array([[1., 1., 1.]]), array([[977, 789, 248]]))
pred: good real: good
-----------------------------------------------------------
(array([[1., 1., 1.]]), array([[1334,  159,  123]]))
pred: good real: good
-----------------------------------------------------------
(array([[1., 1., 1.]]), array([[ 694,  885, 1542]]))
pred: good real: good
------------------------------------------

###LDA algorithm

LDA =======>>>> y = ax+b

In [33]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [34]:
DisAnsModel = LinearDiscriminantAnalysis()

In [35]:
DisAnsModel.fit(x_train, y_train)

LinearDiscriminantAnalysis()

In [36]:
DisAnsModel.score(x_test, y_test)

0.735632183908046

In [37]:
DisAnsModel.score(x_train, y_train)

0.6873857404021938